service: api-wars

plugins:
  - 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

package:
  exclude:
    - .serverless/**
    - cache/**
    - reports/**
    - test/**

functions:
  planets:
    timeout: 120
    handler: src/lambdaPlanets.handler
    events:
      - http:
          path: /planets
          method: any
  species:
    timeout: 120
    handler: src/lambdaSpecies.handler
    events:
      - http:
          path: /species
          method: any

  people:
    timeout: 120
    handler: src/lambdaPeoples.handler
    events:
      - http:
          path: /wars
          method: any
          
  swagger:
    timeout: 120
    handler: src/lambdaSwagger.handler
    events:
      - http:
          path: /{any+}
          method: any
